spring:
  application:
    name: gatewat-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: xiaobai_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: admin_route
          uri: lb://lot
          predicates:
            - Path=/api/loT/**
          filters:
            - StripPrefix=1
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

server:
  port: 8001

management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
logging:
  level:
    com.xiaobai: debug