server:
  port: 18089
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.147.218:3306/xiaobaidb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Abcde@123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:7001/eureka
#  instance:
#    prefer-ip-address: true
#feign开启熔断，默认是线程池策略
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE